#!/usr/bin/node

const rl = require('readline-sync');

function fibonnaci(number)
{
	let array = [0, 1];
	for (let i = 2; i < number; ++i) 
		array[i] = array[i - 1] + array[i - 2];

	return array;
}

console.log(fibonnaci(10));
